Feature/223 integration citation for deaccessioned dataset
IQSS/dataverse-frontend pull request #247
Opened 2023-12-02 22:19 UTC by ekraffmiller

## What this PR does / why we need it:
Update package.json to use dataverse-client-javascript that returns deaccessioned dataset, add Story and e2e test for Deaccessioned Dataset
## Which issue(s) this PR closes:

- Closes #223 

## Special notes for your reviewer:
Please ignore the commits to AccessFileMenu.tsx, I thought I needed to change the rendering logic, but it was working correctly, so reverted it back.  

## Suggestions on how to test this:
Run the e2e test, view the Deaccessioned Dataset 

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No
## Is there a release notes update needed for this change?:
No
## Additional documentation:

2023-12-13 10:35 UTC, MellyGray commented
@ekraffmiller is this issue ready for review? can you change the PR from draft to ready for review? also, can you take a look at the conflicts?

2023-12-19 14:03 UTC, MellyGray requested changes

2023-12-19 14:03 UTC, MellyGray commented on package.json
> +    "@iqss/dataverse-client-javascript": "2.0.0-pr105.779a3f4",
I think the library version needs to be updated why the last changes that include the includeDeaccessioned flag as an argument of the use case

2023-12-19 14:03 UTC, MellyGray commented on tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx
>        // TODO - Implement once the getDatasetCitation includes deaccessioned datasets
We can remove the TODO comment since getDatasetCitation is already implemented

2023-12-19 15:49 UTC, ekraffmiller commented
Thanks @MellyGray , I made the requested changed

2023-12-19 17:36 UTC, ekraffmiller commented
@MellyGray  The e2e test is failing, I think it is still the timing error caused by the FilePermissions Hook. Even though the error is different, the fact that it's happening at the same place and only happens intermittently makes me suspicious.  :( 
The error is only happening in Github, I can't reproduce it locally.

As we talked about before, when I tried to solve the timing error by refactoring the permissions, I just simplified the hooks, I didn't remove them altogether.  Maybe we should create a new ticket to do that? I have my code from before saved in another branch, so I think I could it wouldn't be too time consuming.

2023-12-20 09:35 UTC, MellyGray commented
@ekraffmiller Sure, go ahead and create the new ticked to remove the permissions hook. I think it makes sense to prioritize the refactor since changes to the File model may affect the new File page

2023-12-20 09:36 UTC, MellyGray approved these changes

2023-12-21 09:44 UTC, GPortas commented
Looks good!

![deaccessionspa](https://github.com/IQSS/dataverse-frontend/assets/17010447/9c461564-d8a6-4d0c-958b-0da431535928)

2023-12-21 09:44 UTC, merged