Fix - Collection page datasets not being refetched after navigating from a sub collection.
IQSS/dataverse-frontend pull request #409
Opened 2024-05-23 14:02 UTC by GermanSaracca

**What this PR does / why we need it**:
Fix bug about datasets from collection not changing when collection changed.

**Which issue(s) this PR closes**:

Closes #408 

**Special notes for your reviewer**:

**Suggestions on how to test this**:
Navigate to a dataset in a sub-collection, then click on the breadcrumbs to go to the parent collection for that dataset.
The datasets in that collection will be displayed, and then click on the breadcrumb root to display the new datasets in the root collection.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No.

**Is there a release notes update needed for this change?**:
No.

**Additional documentation**:
No.

2024-05-29 21:39 UTC, ekraffmiller requested changes
There is one difference in the Chromatic build,    https://www.chromatic.com/test?appId=646f68aa9beb01b35c599acd&id=664f41fbb2649c10c264b47b which I think is caused by Chromatic taking the snapshot before the page finishes loading. To avoid that other stories have a parameter to delay the snapshot, for example, here:
https://github.com/IQSS/dataverse-frontend/blob/2ec048c2098f8d01c3485e3bb4a8df9a8134df08/src/stories/dataset/Dataset.stories.tsx#L24C3-L27C4
I think if we add that delay to CreateDataset.stories.tsx, the Chromatic build will pass

2024-05-30 11:32 UTC, GermanSaracca commented
@ekraffmiller I added the delay (_also rename story file from DatasetCreate to CreateDataset_), I see now that snapshots are correctly being captured after the delay.
In the case of the Default Story, the snapshots shows now the actual form and not only the loading skeletons. Thanks!

2024-05-30 12:09 UTC, ekraffmiller approved these changes
Looks good!  I accepted the Chromatic changes.  Approved!

2024-06-06 15:48 UTC, GPortas approved these changes
Works good!

https://github.com/IQSS/dataverse-frontend/assets/17010447/82644473-95cc-4f27-bd5b-e69c2064efe4

2024-06-06 15:49 UTC, merged