448: fix link in files table
IQSS/dataverse-frontend pull request #452
Opened 2024-08-07 13:11 UTC by ekraffmiller

**What this PR does / why we need it**:
Adds versionNumber to the FilePreview object so it can be used in the link to the File Page from the files table

**Which issue(s) this PR closes**:

Closes #448 

**Special notes for your reviewer**:

**Suggestions on how to test this**:
Create a dataset that has a file.  Edit Dataset and publish the dataset multiple times to create multiple versions. Go to an older version of the Dataset Page by using the version param.  In the files table of the Dataset Page, click on the file link.  It should go to the File Page showing the same version as the dataset.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No
**Is there a release notes update needed for this change?**:
No
**Additional documentation**:

2024-08-12 12:05 UTC, GermanSaracca requested changes
Nice work, just a comment about the error throwing.

2024-08-12 14:30 UTC, ekraffmiller commented on src/sections/dataset/dataset-files/files-table/file-info/file-info-cell/file-info-data/FileTitle.tsx
> +      searchParams={{ id: id.toString(), datasetVersion: datasetVersionNumber.toSearchParam() }}>
The filePreview param should always have datasetVersion...would it be better to create modified type, like this?
```
export interface FilePreviewWithDatasetVersion extends Omit<FilePreview, 'datasetVersion'> {
  datasetVersion: DatasetVersionNumber
}
```

2024-08-12 18:56 UTC, ekraffmiller commented
@GermanSaracca I think you are right that changing the interface introduced more changes than was necessary for that small piece of logic, so I added a check for null as suggested 👍

2024-08-12 18:58 UTC, ekraffmiller commented on src/sections/dataset/dataset-files/files-table/file-info/file-info-cell/FileInfoCell.tsx
> +    throw new Error('FilePreview object must contain datasetVersionNumber')
Agreed, I added a check for undefined, which returns null

2024-08-13 11:18 UTC, g-saracca submitted a review, later dismissed
Looks good, approving!

2024-08-21 09:24 UTC, GPortas commented
For when you are back, can you please resolve the conflicts? thanks! @ekraffmiller

2024-08-22 11:45 UTC, g-saracca commented
@GPortas I have resolved merge conflicts, can you take a look if everything still looks fine?

2024-08-23 12:47 UTC, GPortas approved these changes
Works good.

https://github.com/user-attachments/assets/019fdc5e-069b-4859-809f-92320e660ad4

2024-08-23 12:48 UTC, merged