Add Breadcrumb to Create Dataset Page
IQSS/dataverse-frontend pull request #486
Opened 2024-09-10 20:29 UTC by ChengShi-1

## What this PR does / why we need it:
In Create Dataset page, we don't have the breadcrumb for the page which is supposed to have.

## Which issue(s) this PR closes:

- Closes #480 

## Special notes for your reviewer:

## Suggestions on how to test this:
1. Log in to the SPA
2. Locate and click on the "Add Data" button in the navigation bar
3. From the dropdown or menu that appears, select "New Dataset"
4. Check the breadcrumb trail at the top of the page. It should display: "Root > Create Dataset"

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
Yes, breadcrumb added.
![image](https://github.com/user-attachments/assets/72b2b66b-ba3f-4017-9ff2-fb8b2f8fbf52)

## Is there a release notes update needed for this change?:
No
## Additional documentation:
No

2024-09-12 13:58 UTC, g-saracca requested changes
Looks good! Congrats on your first PR @ChengShi-1 ! 🎉  
Just some minor changes and if you could please add the change I mentioned in the core-spa channel about the upload-artifact version so we can see that the component tests run correctly.

2024-09-12 13:58 UTC, g-saracca commented on src/sections/create-dataset/CreateDataset.tsx
> +import { CreateDatasetSkeleton } from './CreateDatasetSkeleton'
Could you add an empty line between this import and the actual component?

2024-09-12 13:58 UTC, g-saracca commented on tests/e2e-integration/e2e/sections/collection/Collection.spec.ts
> +    cy.get(`.breadcrumb`)
You can discard these assertions of the breadcrumb in this test as they are already being asserted in the CreateDataset spec

2024-09-12 17:13 UTC, g-saracca submitted a review, later dismissed
Looks good! approving! 🚀

2024-09-12 20:49 UTC, ekraffmiller requested changes
Looks great, just requesting a clean up of older code in the e2e test

2024-09-13 13:39 UTC, ekraffmiller approved these changes
thanks for removing the wait() calls,  approved!

2024-09-13 13:39 UTC, merged