Feat/461 publish collection
IQSS/dataverse-frontend pull request #500
Opened 2024-09-23 15:29 UTC by ekraffmiller

## What this PR does / why we need it:

## Which issue(s) this PR closes:

- Closes #461 

## Special notes for your reviewer:

## Suggestions on how to test this:

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:

## Is there a release notes update needed for this change?:

## Additional documentation:

2024-09-27 13:22 UTC, g-saracca requested changes
Looks good, just a few comments on things to improve

2024-09-27 13:22 UTC, g-saracca commented on src/stories/collection/publish-collection/PublishCollectionModal.stories.tsx
> +      handleClose={() => {}}></PublishCollectionModal>
auto close tag />

2024-09-27 13:22 UTC, g-saracca commented on tests/e2e-integration/e2e/sections/collection/Collection.spec.ts
> +        cy.findByText('Unpublished').should('not.exist')
could be good to assert that the Publish button doesnt exist anymore.

2024-10-01 13:57 UTC, ekraffmiller commented on src/sections/collection/PublishCollectionButton.tsx
> +      <Button
If we add a ButtonGroup, it would have to be in the Collection component, right? Or another component that contains all of the buttons?

2024-10-01 14:20 UTC, g-saracca commented on src/sections/collection/PublishCollectionButton.tsx
> +      <Button
hmm good question, ok lets keep it simple as it is for now.

2024-10-02 11:23 UTC, g-saracca approved these changes
Thanks for addressing the requested changes, all the Storybook check reviews look good also, approving!

2024-10-03 18:58 UTC, g-saracca commented on src/sections/collection/Collection.module.scss
> +  margin-bottom: 10px;
```suggestion
  margin-bottom: 1rem;
```

2024-10-03 19:02 UTC, g-saracca submitted a review, later dismissed

2024-10-10 19:42 UTC, g-saracca approved these changes

2024-10-10 20:02 UTC, ofahimIQSS commented
Testing completed in local. No issues found during testing. 
[Testing 500.docx](https://github.com/user-attachments/files/17333599/Testing.500.docx)

2024-10-10 20:05 UTC, merged