Feat/425 publish dataset and collection
IQSS/dataverse-frontend pull request #520
Opened 2024-10-09 10:06 UTC by ekraffmiller

## What this PR does / why we need it:

## Which issue(s) this PR closes:

- Closes #

## Special notes for your reviewer:

## Suggestions on how to test this:

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:

## Is there a release notes update needed for this change?:

## Additional documentation:

2024-10-10 18:30 UTC, g-saracca commented
Hi @ekraffmiller could you update js-dataverse package version with `2.0.0-alpha.2`, https://github.com/IQSS/dataverse-client-javascript/pull/199 is already merged, thanks!

2024-10-14 13:22 UTC, g-saracca requested changes
@ekraffmiller , looks awesome! just some minor comments and there is a conflict in package.json

2024-10-15 14:20 UTC, ekraffmiller commented on tests/component/sections/dataset/dataset-publish/PublishDatasetModal.spec.tsx
> +    collectionRepository.publish = cy.stub().as('collectionRepositoryPublish').resolves()
Good point, I will add to test that it is called

2024-10-15 16:08 UTC, g-saracca approved these changes
Looks great! thanks, approving!

2024-10-16 15:40 UTC, ofahimIQSS commented
tested in local - no issues found. 
[Testing of 520.docx](https://github.com/user-attachments/files/17398519/Testing.of.520.docx)

2024-10-16 15:40 UTC, merged