Add time tag to the date and change some date format to YYYY/MM/DD
IQSS/dataverse-frontend pull request #541
Opened 2024-11-04 17:14 UTC by ChengShi-1

## What this PR does / why we need it:
For solving some existing todos, add time tag to the date so as to provides semantic meaning to the content. The date attribute within the <time> tag allows you to provide a machine-readable format of the date and time, which can be useful for search engine optimization (SEO), calendar integration, and other purposes. Also, in order to keep constant with JSF, we need change some date format to YYYY/MM/DD as well.

## Which issue(s) this PR closes:

- Closes #533 

## Special notes for your reviewer:

## Suggestions on how to test this:
Step 1: Run the Development Environment

1. Execute npm i.
2. Navigate with cd packages/design-system && npm run build.
3. Return with cd ../../.
4. Ensure you have a .env file similar to .env.example, with the variable VITE_DATAVERSE_BACKEND_URL=http://localhost:8000/.
5. Navigate with cd dev-env.
6. Start the environment using ./run-env.sh unstable.
7. To verify the environment, visit http://localhost:8000/ and check your local Dataverse installation.

Step 2: check if the date run well and in a right format YYYY/MM/DD
1. log in 
2. create a new dataset
3. upload a random file
4. under "File Metadata", click the file title, "Deposit Date" should be shown in YYYY-MM-DD format.
5. publish the dataset
6.under "File Metadata", click the file title, the filed "Deposit Date","Metadata Release Date", and "Publication Date" should be shown in YYYY-MM-DD format.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:

## Is there a release notes update needed for this change?:

## Additional documentation:

2024-11-08 12:11 UTC, g-saracca requested changes
Hi @ChengShi-1 , leave some comments on test files and we are missing `datetime` attribute on all the `<time />` tags.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

2024-11-08 12:11 UTC, g-saracca commented on src/sections/file/file-metadata/FileMetadata.tsx
> +                  <time>
With this logic if there is no `publicationDate` you will still render an empty <time/> tag, try to check if exits and  then render the tag

2024-11-08 12:11 UTC, g-saracca commented on tests/component/sections/file/file-embargo/FileEmbargoDate.spec.tsx
> +    const dateString = embargoDate.toISOString().split('T')[0]
You could use the DateHelper here instead of repeating code

2024-11-08 12:11 UTC, g-saracca commented on tests/component/sections/file/file-embargo/FileEmbargoDate.spec.tsx
> +    const dateString = embargoDate.toISOString().split('T')[0]
Same here, use DateHelper

2024-11-08 12:11 UTC, g-saracca commented on tests/component/sections/file/file-embargo/FileEmbargoDate.spec.tsx
> +    const dateString = embargoDate.toISOString().split('T')[0]
Same, DateHelper

2024-11-08 12:11 UTC, g-saracca commented on tests/component/sections/file/file-embargo/FileEmbargoDate.spec.tsx
> +    const dateString = embargoDate.toISOString().split('T')[0]
Could use date helper also

2024-11-08 18:54 UTC, ChengShi-1 commented
> Hi @ChengShi-1 , leave some comments on test files and we are missing `datetime` attribute on all the `<time />` tags. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

Hi German! Thank you a lot for reviewing it! I submit a couple of fix here. The earliest fix included most of the adjustments, but the dateHelper in utcTime couldn't pass the e2e so I had next two fix commits for recovering the code. Sorry for messed commits, hope you are not confused.

2024-11-08 21:47 UTC, g-saracca requested changes
Some more tweaks for the datetime attribute value

2024-11-08 21:47 UTC, g-saracca commented on src/sections/dataset/dataset-files/files-table/file-info/file-info-cell/file-info-data/FileDate.tsx
> +        <time dateTime={DateHelper.toDisplayFormat(date.date)}>
datetime value is the machine-readable value of the datetime, so in there you shouldn't use the `displayFormat` which is a a more human readable but the `toISO8601Format` one.

2024-11-08 21:47 UTC, g-saracca commented on src/sections/file/file-embargo/FileEmbargoDate.tsx
> +            format === 'YYYY-MM-DD'
datetime value is the machine-readable value of the datetime, so in there you shouldn't use the `displayFormat` which is a a more human readable but the `toISO8601Format` one.

2024-11-11 11:23 UTC, g-saracca approved these changes

2024-11-12 20:19 UTC, ofahimIQSS commented
@ChengShi-1  It looks like file uploading is broken with this PR 😫. 
1. Go to http://localhost:8000/
2. Login
3. Add dataset and add a file to upload (i tried several file types all of them failed)
Result: Once you upload the file, the file disappears and is not displayed on the UI. See video below

I was thinking it might be a local issue but wanted to check with you guys first. 

https://github.com/user-attachments/assets/685f32e4-05a2-41d9-8147-a0ce6bd86599

2024-11-12 21:51 UTC, ChengShi-1 commented
> @ChengShi-1 It looks like file uploading is broken with this PR 😫.
> 
> 1. Go to http://localhost:8000/
> 2. Login
> 3. Add dataset and add a file to upload (i tried several file types all of them failed)
>    Result: Once you upload the file, the file disappears and is not displayed on the UI. See video below
> 
> I was thinking it might be a local issue but wanted to check with you guys first.
> 
>  Screen.Recording.2024-11-12.at.3.15.20.PM.mov

Hi, Omer! Sorry, it should be for http://localhost:8000/spa instead of JSF(http://localhost:8000). Can you try
http://localhost:8000/spa/datasets/root/create to create, and then click into the dataset you just create, and "Upload Files" button here.
![image](https://github.com/user-attachments/assets/7402472a-f8a5-401b-8d01-72dcd58cbccd)

2024-11-13 18:56 UTC, ofahimIQSS commented
@ChengShi-1 The file upload is still failing, see recording below:


https://github.com/user-attachments/assets/d464f8d0-4810-4ef8-9a7a-a1de0b28156a

2024-11-14 14:30 UTC, ChengShi-1 commented
> @ChengShi-1 The file upload is still failing, see recording below:
> 
> 1. Login, Created new dataset in SPA
> 2. Saved
> 3. Add an image file to dataset
>    Issue: When trying to upload the image, file appears red and is not uploaded to system
> 
>  Screen.Recording.2024-11-13.at.1.53.35.PM.mov

@ofahimIQSS Hi Omer, I don't meet the same uploading error on my end. Since I don't think this PR changes the code about uploading, could you try upload files in other branch to see if the uploading failure happens globally, and rebuild docker to try upload again as well? Ty!

2024-11-18 16:49 UTC, merged